export const loadingTexts = [
    "Consulting the elves...",
    "Herding the cats...",
    "Polishing the pixels...",
    "Waking up the hamsters...",
    "Brewing digital coffee...",
    "Untangling the spaghetti code...",
    "Summoning the creativity fairy...",
    "Asking the rubber duck...",
    "Charging the flux capacitor...",
    "Aligning the chakras...",
    "Convincing the AI to cooperate...",
    "Translating binary to poetry...",
    "Searching for the lost semicolon...",
    "Feeding the server squirrels...",
    "Painting the loading bar...",
    "Calculating the meaning of life...",
    "Reversing the polarity...",
    "Spinning the wheel of fortune...",
    "Consulting the oracle...",
    "Dusting off the old manuals...",
    "Negotiating with the bits...",
    "Teaching the AI to sing...",
    "Looking for the 'any' key...",
    "Optimizing the vibes...",
    "Downloading more RAM...",
    "Compiling the magic...",
    "Whispering to the cloud...",
    "Juggling the data packets...",
    "Unicorns are running...",
    "Gnomes are mining data...",
    "Wizards are casting spells...",
    "Robots are doing the robot...",
    "Aliens are phoning home...",
    "Time traveling to the future...",
    "Reading the tea leaves...",
    "Stargazing for answers...",
    "Chasing the white rabbit...",
    "Opening the pod bay doors...",
    "Engaging warp drive...",
    "Assembling the avengers...",
    "Baking fresh cookies...",
    "Watering the plants...",
    "Tuning the radio...",
    "Solving a Rubik's cube...",
    "Playing hide and seek...",
    "Counting the stars...",
    "Catching fireflies...",
    "Building a sandcastle...",
    "Flying a kite...",
    "Dreaming of electric sheep..."
];
